### PR TITLE
Quick and dirty subnet restriction.

### PR DESCRIPTION
**Pull request by turboaaa**
Providing a quick way to restrict access to private subnets only

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi,

I'm not sure about this one, the purpose of this container is simplicity and I'm really not that worried about the use of it outside containers. 

I think it would be more useful then to be able to set the mynetworks parameter altogether with an env var and let the user configure it as they need to according to their setup, like this [PR](https://github.com/juanluisbaptiste/docker-postfix/pull/5) was trying to do (but it was abandoned by its author).

**Comment by turboaaa** [comment]
Of course I would be using this in a way you did not intend lol.

Since you do not intend for it to be used outside of the container network, do we even want to specify any networks?

**Comment by turboaaa** [comment]
This sounds like a good idea.

**Comment by juanluisbaptiste** [comment]
Could you please create a new PR with a clean state of the changes ? there are a lot of commits there that aren't needed and will only add noise to the commit log.

**Comment by turboaaa** [comment]
Sure, no problem.

**Comment by juanluisbaptiste** [comment]
Continued on PR #12

**Pull request closed without merging**
