### PR TITLE
Replace add_config_value with native postconf

### PR DESCRIPTION
**Pull request by turboaaa**
This project saved me a lot of time. With the basic service running in docker I was able to add TLS and authentication for external clients. I am hoping I can help in some small way.

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi,

Thanks for the PR, please modify the commit message to specify all the changes, not only the change to postconf but also that you added an additional configuration option  "smtp_sasl_tls_security_options = noanonymous".

**Comment by turboaaa** [comment]
I need to go back and verify why I have that in there. I think it was related to the authentication for clients to connect with, and it got copied into my changes by accident. If this ends up being the case we can remove it from this request. There are several pull requests I want to submit for review as time permits.

Hoping to get back to you tomorrow. Again, thanks for the work you put into this!

**Comment by turboaaa** [comment]
So it looks like the "smtp_sasl_tls_security_options" line was from my notes when I first setup my old relay. This page ( http://www.postfix.org/SASL_README.html ) reports that it

"...removes the prohibition on plaintext passwords."

Not sure if this is really a good thing, but the example provided does show the "smtp_tls_security_level = encrypt" option being set, with a description of

"ensures that the connection to the remote smtp server will be encrypted"

So if we leave in "smtp_sasl_tls_security_options" we probably want to enforce encryption. Thoughts? If needed we can yank it from this request and create a new one for these minor options.

**Comment by turboaaa** [comment]
I did find an unexpected difference between how the emails are received by the server.

Headers
With function : Content-Type: text/plain; charset="us-ascii”
With postconf : Content-Type: application/ms-tnef; name="winmail.dat"

There is an impact to how exchange online sees these messages. With winmail.dat, exchange pushes the email through to the recipient inbox without question. If the header reports us-ascii, spam filters come into play and will dump the email into junk email.

I found this difference because I was adding a header to exchange to match against (one more layer of "authentication") and not send the emails to spam. While working on an additional pull request with this change added, I started to pull my hair out as to why the headers were not showing up.

The postconf process takes care of this for me, but it does remove my ability to modify headers. Do you have any idea as to why this might be?

**Comment by juanluisbaptiste** [comment]
> Not sure if this is really a good thing, but the example provided does show the "smtp_tls_security_level = encrypt" option being set, with a description of
> 
> "ensures that the connection to the remote smtp server will be encrypted"
> 
> So if we leave in "smtp_sasl_tls_security_options" we probably want to enforce encryption. Thoughts? If needed we can yank it from this request and create a new one for these minor options.

I think it could be a good idea but let discuss it in a separate PR, this one is about the change to postfonf.

**Comment by juanluisbaptiste** [comment]
> I found this difference because I was adding a header to exchange to match against (one more layer of "authentication") and not send the emails to spam. While working on an additional pull request with this change added, I started to pull my hair out as to why the headers were not showing up.
> 
> The postconf process takes care of this for me, but it does remove my ability to modify headers. Do you have any idea as to why this might be?

Excellent you found this but I have no idea why it could happen.

**Comment by turboaaa** [comment]
Removed "smtp_sasl_tls_security_options = noanonymous" as discussed. Will create a seperate PR for this and it's companion setting.

**Comment by juanluisbaptiste** [comment]
Yes, I think it would be better so you know at startup which configuration is running.

**Comment by turboaaa** [comment]
I have not abandoned this, deadlines at work and family life are draining my energy. Worked over the weekend. Would like to take a day off this week to make these changes and test.

**Comment by juanluisbaptiste** [comment]
I'm sorry I took so long.

**Pull request merged**
