### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by michaeldg**
Hey,

I came across your little project looking to build a smart relay that could temporarily hold mail. Not finding one I decided to find out how to do it, concluded it is not easy in exim, and then came to your postfix image.

I have not implemented any code, but I think the documentation should be helpful for people trying to achieve the same.

Michaël

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi,

Nice idea but I will not accept anything that needs manual interaction with the running container, it needs to be able to be controlled with env variables.

**Comment by michaeldg** [comment]
Hi,

I don't think that is possible for all cases I want to support because (please correct me if I'm wrong, I am not that proficient with docker) changing the configuration requires restarting the container.

 Imagine a scenario where there is mail in the hold queue that needs to be delivered but not right now. If the user forgot to create a persistent volume for the hold queue, that mail is gone. Next to that, if there was a persistent volume for the hold queue, postfix would send it out immediately upon restart.

With the procedure I suggested you 'catch' these scenario with `postsuper -h ALL` to the running postfix, holding the entire queue.

Whilst I agree with your principle in general, I think this is part of a maintenance scenario. I don't mind doing (documented) things by hand when I am performing maintenance.

Let me know if you see a better way supporting those scenario's!

Thanks,
Michaël

**Comment by juanluisbaptiste** [comment]
I'm sorry then, but the idea of containers is that you don't have to manually intervene to do maintenance, containers should be stateless. So I'm closing this until a better option that can both be controlled by en vars or other way that does not require manual intervention is available.

**Comment by juanluisbaptiste** [comment]
Doing a quick search  using something like [MailHog](https://github.com/mailhog/MailHog) seem to be a better option for what you need to do, it has a web interface and all from were you can retain and see the emssages and release them at will.

**Comment by michaeldg** [comment]
Thank you for the research, but to me MailHog seams to be a development tool, while I plan to use this smart relay in production. I will use the container the way I documented.

**Pull request closed without merging**
