### PR TITLE
feat: Parameterize mydestination config value

### PR DESCRIPTION
**Pull request by natzert**
## Description of the change

I need to be able to modify the `mydestination` config value and do not want to track my own ad hoc modifications to this repo.

## Motivation and Context

Allows modifying `mydestination` as an environment var instead of modifying `run.sh`

## How Has This Been Tested?

Tested in GKE. Existing cluster relays messages to external mail forwarder.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation (adding or updating documentation)

## Checklist:

- [X] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] My change adds a new configuration variable and I have updated the `.env.example` file accordingly.

And lastly, many thanks for taking your time to help us improve this project !

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi @natzert, thanks for the PR, I will check it out as soon as I can.

**Comment by juanluisbaptiste** [comment]
Testing with the default values (`mydestination = localhost`) it seems it breaks upstream authentication:

```
postfix_1  | Jul 07 17:14:13 jbtech postfix/smtp[113]: 50263C6: SASL authentication failed; server smtp.xxxx.net[xxx.xxx.xxx.xxx said: 535 Authentication failed: Bad username / password
```

If I test with master it works fine.

**Comment by natzert** [comment]
@juanluisbaptiste You're right. Misunderstood my own config. The original line creating sasl_passwd file was correct. I've reverted that change.

**Comment by juanluisbaptiste** [comment]
Now it works.

**Comment by juanluisbaptiste** [comment]
Merged, TY.

**Pull request merged**
