### PR TITLE
feat: Allow disabling SMTPUTF8

### PR DESCRIPTION
**Pull request by envy**
# Creating a Pull Request

We use github actions to do automatic [semantic versioning](https://github.com/semantic-release/semantic-release), so please use the following nomenclature for the commit message according to the type of change:

* Prefix with `feat:`, and it will trigger a minor version bump. 
* Prefix with `fix`:, and it will trigger a patch version bump. 
* Prefix with `BREAKING CHANGE:`, and it will trigger a major version bump.

## Description of the change

This PR adds an option to disable SMTPUTF8. 

## Motivation and Context

We use this container in our deployments to relay emails to mailbox.org which does not support SMTPUTF8. I think there are probably many other providers who don't support this option and therefore need to disable it.

## How Has This Been Tested?

We use this change in production in our product.

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation (adding or updating documentation)

## Checklist:

- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] My change adds a new configuration variable and I have updated the `.env.example` file accordingly.

And lastly, many thanks for taking your time to help us improve this project !

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi @envy sorry for the late reply, I will try to review this this week.

**Comment by juanluisbaptiste** [comment]
Hi @envy please amend the commit message and add "feat: " to the beginning of it, and also the PR needs to be rebased as I have been merging other PRs.

Sorry for the delay

**Comment by envy** [comment]
Hi, done.

**Comment by juanluisbaptiste** [comment]
@envy thanks, I merged the code, but for some reason the github release action did not trigger, so I'm looking into that.

**Pull request merged**
