### PR TITLE
feat: Add message_size_limit option

### PR DESCRIPTION
**Pull request by nassoor**
## Description of the change

This adds the message_size_limit option to enable changing the default value.

## Motivation and Context

To enable sending larger messages

## How Has This Been Tested?

Tested the change with a value of 34000000 (34MB) 

## Types of Changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation (adding or updating documentation)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My change requires a change to the documentation and I have updated the documentation accordingly.
- [x] My change adds a new configuration variable and I have updated the `.env.example` file accordingly.

And lastly, many thanks for taking your time to help us improve this project !

### CODE REVIEW

**Comment by TheFlyingBadger** [comment]
Winner! I was just about to do a PR for this myself....

**Comment by juanluisbaptiste** [comment]
Hi @nassoor, thanks for the PR, but it currently needs rebasing.

**Comment by nassoor** [comment]
Done

**Comment by juanluisbaptiste** [comment]
@nassoor Sorry for the late reply, thanks for the rebasing but I merged a previous PR and it needs again rebasing. Please rebase against master again and I will merge inmediately. TY

**Comment by nassoor** [comment]
Done 👍

**Comment by juanluisbaptiste** [comment]
@nassoor there is still something missing as the PR still says it cannot be rebased due to conflicts.

**Comment by nassoor** [comment]
GitHub does not show me anything like that, quite the opposite.

https://github.com/juanluisbaptiste/docker-postfix/compare/master...nassoor:master

**Comment by nassoor** [comment]
I can recreate the PR if necessary.

**Comment by juanluisbaptiste** [comment]
This is what appears on the PR:
Screenshot_20220523_231550

**Comment by nassoor** [comment]
I will recreate.

**Pull request closed without merging**
