### PR TITLE
feat: add GitHub CI and Docker release

### LINKED ISSUE #23: Docker image for Raspberry Pi
I noticed that there's only an amd64 image of this container on Docker Hub.

I just checked out the `migrate_to_alpine` branch, built the container with `docker build -t postfix .` and I can confirm that the resulting container just works on a Raspberry Pi running Raspbian 10.3. Could you also publish arm builds of the image to Docker Hub?

### PR DESCRIPTION
**Pull request by ViRb3**
This PR uses GitHub Workflows to fully automate the release process:
- Automatically version using semantic-release
- Create tag with above version
- Create release with changelog
- Build Docker multi-arch images using buildx (fixes #23)
- Publish Docker images

I configured the CI for the `migrate_to_alpine` branch as Alpine fits my needs better, and the releases are labeled as "prereleases", suffixed with "alpine-rc". Sample build can be found here: https://hub.docker.com/repository/docker/virb3/docker-postfix

To use this yourself, simply add the following secrets to your GitHub repo:
- API_GITHUB_TOKEN
- DOCKER_USERNAME
- DOCKER_PASSWORD

Additionally, change `export REPO="virb3/${REPO}"` in `.github/workflows/release.yml` to your namespace on Docker Hub.

I am happy to provide support and customize the workflow to your desire.

### CODE REVIEW

**Comment by juanluisbaptiste** [comment]
Hi,

Thank you, as I'm not familiar with github CI I will have to review it to get familiar with it, I already have my own CI setup with drone to build and push new images to docker hub and have been working fine so far, but the mutiarch stuff is nice too.

I will review this PR as soon as possible.

Thanks again.

**Comment by ViRb3** [comment]
No rush at all. I use Drone extensively, but unfortunately it is not suitable for this task. Emulated multi-arch, like the one in this PR, is impossible with Drone Cloud, as you need access to the docker socket and that is not allowed on the cloud deployment. GitHub on the other hand provides you with a full virtual machine, so you can easily access the Docker socket to make everything work. If you need any help or explanations let me know.

**Comment by juanluisbaptiste** [comment]
Hi @ViRb3 I am sorry I did not pay attention to your PR, I got caught with other things and it slipped through the cracks, my apologies.

Do you have the time to take a look at it and update it to work with the the latest version of this image if necessary ? I have little experience with github actions.

**Comment by ViRb3** [comment]
Hey, no problem at all. I am a little busy myself right now, but I should be able to update this PR in the next few days. A good amount of things changed since I made the PR so things should be even smoother now.

**Comment by juanluisbaptiste** [comment]
Excellent man, thanks !

**Comment by ViRb3** [comment]
Superseded by #52

**Pull request closed without merging**
